In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

In [4]:
sales = pd.read_csv('Data/sales_data.csv', parse_dates=['Date'])

sales.head()


Date  Day     Month  Year  Customer_Age       Age_Group  \
0 2013-11-26   26  November  2013            19     Youth (<25)   
1 2015-11-26   26  November  2015            19     Youth (<25)   
2 2014-03-23   23     March  2014            49  Adults (35-64)   
3 2016-03-23   23     March  2016            49  Adults (35-64)   
4 2014-05-15   15       May  2014            47  Adults (35-64)   

  Customer_Gender    Country             State Product_Category Sub_Category  \
0               M     Canada  British Columbia      Accessories   Bike Racks   
1               M     Canada  British Columbia      Accessories   Bike Racks   
2               M  Australia   New South Wales      Accessories   Bike Racks   
3               M  Australia   New South Wales      Accessories   Bike Racks   
4               F  Australia   New South Wales      Accessories   Bike Racks   

               Product  Order_Quantity  Unit_Cost  Unit_Price  Profit  Cost  \
0  Hitch Rack - 4-Bike               8         45         120     590   360   
1  Hitch Rack - 4-Bike               8         45         120     590   360   
2  Hitch Rack - 4-Bike              23         45         120    1366  1035   
3  Hitch Rack - 4-Bike              20         45         120    1188   900   
4  Hitch Rack - 4-Bike               4         45         120     238   180   

   Revenue  
0      950  
1      950  
2     2401  
3     2088  
4      418

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

In [5]:
sales.shape
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype         
---  ------            --------------   -----         
 0   Date              113036 non-null  datetime64[ns]
 1   Day               113036 non-null  int64         
 2   Month             113036 non-null  object        
 3   Year              113036 non-null  int64         
 4   Customer_Age      113036 non-null  int64         
 5   Age_Group         113036 non-null  object        
 6   Customer_Gender   113036 non-null  object        
 7   Country           113036 non-null  object        
 8   State             113036 non-null  object        
 9   Product_Category  113036 non-null  object        
 10  Sub_Category      113036 non-null  object        
 11  Product           113036 non-null  object        
 12  Order_Quantity    113036 non-null  int64         
 13  Unit_Cost         113036 non-null  int64         
 14  Unit

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

In [6]:
#Analise descritiva do conjunto de dados
sales.describe()

Day           Year   Customer_Age  Order_Quantity  \
count  113036.000000  113036.000000  113036.000000   113036.000000   
mean       15.665753    2014.401739      35.919212       11.901660   
std         8.781567       1.272510      11.021936        9.561857   
min         1.000000    2011.000000      17.000000        1.000000   
25%         8.000000    2013.000000      28.000000        2.000000   
50%        16.000000    2014.000000      35.000000       10.000000   
75%        23.000000    2016.000000      43.000000       20.000000   
max        31.000000    2016.000000      87.000000       32.000000   

           Unit_Cost     Unit_Price         Profit           Cost  \
count  113036.000000  113036.000000  113036.000000  113036.000000   
mean      267.296366     452.938427     285.051665     469.318695   
std       549.835483     922.071219     453.887443     884.866118   
min         1.000000       2.000000     -30.000000       1.000000   
25%         2.000000       5.000000      29.000000      28.000000   
50%         9.000000      24.000000     101.000000     108.000000   
75%        42.000000      70.000000     358.000000     432.000000   
max      2171.000000    3578.000000   15096.000000   42978.000000   

             Revenue  
count  113036.000000  
mean      754.370360  
std      1309.094674  
min         2.000000  
25%        63.000000  
50%       223.000000  
75%       800.000000  
max     58074.000000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Numpy quick overview

In [85]:
#[] cada conjunto de colchetes se lê como as linhas, e cada elemento dentro do conjumento se le como colunas por elemento
# aqui se lê um array de 3 Linhas e 4 Colunas
#Obs a quantidade de elementos dentro dos conjuntos deve ser a mesma, caso não seja, deve-se especificar o tipo Object em dtype
mx_A = np.array([[1,2,3,10], [4,5,6,11], [7,8,9,10]], dtype=np.int8)

#Nao da erro por deixar explicito o tipo Object, mas não sei exatamente o impacto e usuabilidade disso.
mx_object = np.array([[1,2], [4,5,6,11], [7,8,9]], dtype=object)

mx_A.size

#Linha,Coluna nesse caso pode-se fazer também o slicing -> Maneira mais eficaz, mas também funciona do jeito raiz A[Linha][Coluna]
print("Slicing: ", mx_A[1:3, :])

print("Raiz: ", mx_A[0][1:3])


Slicing:  [[ 4  5  6 11]
 [ 7  8  9 10]]
Raiz:  [2 3]


In [71]:
#Para cubos aninhados a leitura é parecida, porém cada Linha representa o grupo maior de colchetes
#Cada conjunto de colchetes interno se lê como a dimensão interna dentro da linha
#Cada elemento dentro do conjunto interno é o total de colunas, nesse caso temos um cubo de 3 Linhas, 2 Dimensões e 4 Colunas

mx_B = np.array([
    [
        [10,20,30,39],
        [10,20,30,39],
    ],
    [
        [60,70,80,89],
        [10,20,30,39],
    ],
    [
        [1,2,3,4],
        [10,20,30,39],
    ]

])

In [33]:
mx_A.dtype


dtype('int32')

In [34]:
mx_A.dtype = np.int8
mx_A.dtype

dtype('int8')

In [53]:
print("Dimensions of the Matrix A: ", mx_A.ndim)
print("Dimensions of the Matrix B: ", mx_B.ndim)

Dimensions of the Matrix A:  2
Dimensions of the Matrix B:  3


In [58]:
print("Shape of the matrix A: ", mx_A.shape)
print("Size of the matrix A", mx_A.size)

print("Shape of the matrix B: ", mx_B.shape)
print("Size of the matrix B", mx_B.size)

Shape of the matrix A:  (3, 4)
Size of the matrix A 12
Shape of the matrix B:  (3, 2, 4)
Size of the matrix B 24


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

> **Numpy oferece funcoes matematicas nativas, que podem ser usadas tanto para o conjunto inteiro ou exclusivamente para Linhas (axis=1) ou Colunas (axis=0)**


In [87]:
#mx_A = np.array([
#   [1,2,3,10],
#   [4,5,6,11],
#   [7,8,9,10]], dtype=np.int8)
#   Soma de todos os elementos das colunas 
mx_A.sum(axis=0)

array([12, 15, 18, 31])

In [88]:
#mx_A = np.array([
#   [1,2,3,10],
#   [4,5,6,11],
#   [7,8,9,10]], dtype=np.int8)
#   Soma de todos os elementos das Linhas
mx_A.sum(axis=1)

array([16, 26, 34])

In [103]:
#Como o multidimensional, usamos o axis=2 para calcular esse eixo
'''
mx_B = np.array([
    [
        [10,20,30,39],
        [10,20,30,39],
    ],
    [
        [60,70,80,89],
        [10,20,30,39],
    ],
    [
        [1,2,3,4],
        [10,20,30,39],
    ]

])
Axis=0 ele calcula primeiro os valores das primeiras linhas de cada conjunto ex: 10+60+1 | 20+70+2 | ...
em seguida ele faz os calculos dos valores da dimensao interna 10+10+10 | 20+20+20 |...

Axis=1 ele calcula os valores das linhas e suas dimensoes 60+10 | 70+20 | 80+30 |...
'''
mx_B.sum(axis=1)

array([[ 20,  40,  60,  78],
       [ 70,  90, 110, 128],
       [ 11,  22,  33,  43]])

In [114]:
mx_result_1 = [(mx_B > 60) & (mx_B < 90)]
print(mx_result_1)

mx_result_2 = mx_B >20
print(mx_result_2)

[array([[[False, False, False, False],
        [False, False, False, False]],

       [[False,  True,  True,  True],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False]]])]
[[[False False  True  True]
  [False False  True  True]]

 [[ True  True  True  True]
  [False False  True  True]]

 [[False False False False]
  [False False  True  True]]]


> **Baixar os notebooks dos exercicios no Fork que eu fiz no meu GitHub para praticar mais essa lib**
 
![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)


### Pandas Series

In [117]:
g7_pop = pd.Series([35.467, 63.951, 80.940, 60.655, 127.061, 64.511, 318.523])

g7_pop.name = "G7 population in millions"

g7_pop

0     35.467
1     63.951
2     80.940
3     60.655
4    127.061
5     64.511
6    318.523
Name: G7 population in millions, dtype: float64

In [121]:
#Implicitamente Pandas.Series criam um array de numpy para manipular os valores, o bacana é que se pode dar nome para a Serie.
#Uma vez criado as series nao da pra alterar mais os index da Series, mas é possível se atribuir os nomes para cada um dos indices

print(type(g7_pop.values))
g7_pop.index

<class 'numpy.ndarray'>


RangeIndex(start=0, stop=7, step=1)

In [123]:
g7_pop.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.655
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 population in millions, dtype: float64

In [126]:
g7_pop['France' : 'United Kingdom']

France             63.951
Germany            80.940
Italy              60.655
Japan             127.061
United Kingdom     64.511
Name: G7 population in millions, dtype: float64